import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Our story", description: "From ByteForge in Kanpur to Pyrros. Hackathons, a hacker house, Execron 1.0, and a new chapter of grants." };

export default function StoryPage() { return <main id="main"><section className="page-hero wrap story-hero"><div className="section-index warm">Pyrros / Our story</div><h1>Built from<br /><em>Kanpur.</em></h1><div className="page-hero-bottom"><p>We started as ByteForge in 2024. Pyrros carries that work forward with a sharper purpose: back young people who are already building.</p><span className="page-hero-mark">24<br />↘<br />26</span></div></section>
  <div className="story-image"><Image src="/pyrros/worktable.png" alt="Editorial artwork of a maker's worktable with a small prototype, tools, paper, and chai" fill priority sizes="100vw" /><span className="story-image-label">Editorial artwork</span></div>
  <section className="wrap story-timeline section-pad"><div className="section-index">A short history</div><div className="timeline"><article><div className="timeline-year">2024</div><div><h2>ByteForge begins.</h2><p>It started in Kanpur with hackathons and workshops. Hack Club recognized the club and supported those first gatherings. ByteForge now appears on the Hack Club map.</p><a href="https://hackclub.com/map/" target="_blank" rel="noopener noreferrer" className="text-link">Explore the map ↗</a></div></article><article><div className="timeline-year">2025</div><div><h2>Four days at IIT Kanpur.</h2><p>We ran a four-day hacker house, bringing builders together to work in the same room. A Lucknow investor backed the effort with ₹2 lakh.</p></div></article><article><div className="timeline-year">2026</div><div><h2>Execron 1.0.</h2><p>A hackathon and workshop at IIT Kanpur. Builders received more than $75,000 in credits from OpenAI, Anthropic, Emergent, Lovable, and Supabase, along with $2,000 in cash prizes and goodies.</p><a href="https://gobitsnbytes.org/events" target="_blank" rel="noopener noreferrer" className="text-link">See the event ↗</a></div></article><article><div className="timeline-year">Next</div><div><h2>The Pyrros grants.</h2><p>We are building a way to put ₹5,000 to ₹20,000 behind promising high school and college projects. The first round will be announced on Instagram.</p><Link href="/grants" className="text-link">Explore the grants ↗</Link></div></article></div></section>
  <section className="story-partners"><div className="wrap"><div className="section-index">Credits made available at Execron</div><div className="partner-words"><span>OpenAI</span><span>Anthropic</span><span>Emergent</span><span>Lovable</span><span>Supabase</span></div></div></section>
  <section className="wrap next-page"><span>The people who made it happen.</span><Link href="/people">Meet the team <span aria-hidden>↗</span></Link></section>
  </main> }
